### ISSUE TITLE
How to create Bootable image

### ISSUE THREAD

**Issue by thatsitipl** [OpenNuvoton/N32905_Linux_BSP#1]
I want to create a Bootable image so that i can run it on an N32905
Thanks for any replay

**Comment by cyliangtw** [comment]
How to download kernel to board, please read section 5.4 of `https://github.com/OpenNuvoton/N32905_Linux_BSP/tree/master/Documents`.
For NAND flash case, please burn NAND-Loader & NVT-Loader in advance. If boot loader execute NVT Loader first and run to kernel, the kernel image should be put into SD1-1 or NAND1-1 FAT partition. 
About writer tool: please refer  `https://github.com/OpenNuvoton/N32905_NonOS_Tool/blob/master/TurboWriter`.
About NandLoader code at: `https://github.com/OpenNuvoton/N32905_NonOS_BSP/tree/master/Loader/NandLoader`
About NVT-Loader code at: `https://github.com/OpenNuvoton/N32905_NonOS_BSP/tree/master/NVT_Loader`

**Comment by thatsitipl** [comment]
Thank you for you quick replay.

**Comment by thatsitipl** [comment]
Sry But i noticed that in Turbowriter wants me to add a Mass Storage device as a board but i want to create the image as a bin and upload it onto a spiflash without a connection to the Bord.
I also wanted to ask how i can enter recovery mode on the Chip.

**Comment by cyliangtw** [comment]
1. For boot from spiflash, in development stage, you should burn spi-loader in advance, then linux-kernel image `conprog.bin` by Turbowriter. 
2. About recovery mode, please open page #4 of the attachment.

[NHS-55FA93-1-IN-1M14.pdf](https://github.com/OpenNuvoton/N32905_Linux_BSP/files/8020063/NHS-55FA93-1-IN-1M14.pdf)

**Comment by thatsitipl** [comment]
But i want to write the kernel boot image to the spiflash using a ch34a1 programmer. Is there any chance of creating this file with Turbowriter?

**Comment by kchuang1** [comment]
No, you cannot use TurboWriter with ch34a1 programmer.
Due to N32905 having a Mask ROM (IBR),  it can communicate with TurboWriter. But, ch34a1 cannot.

**Comment by cyliangtw** [comment]
@thatsitipl , it's tool issue and it's better to open this kind tool issue in this repo. https://github.com/OpenNuvoton/N32905_NonOS_Tool/blob/master/TurboWriter 

Anyway, you could follow `1.8. SPI Flash – Raw Data` of Turbo-writer user guide, to make spi-rom image with loader + kernel image.

**Comment by thatsitipl** [comment]
Thank you for all your help. :)
