### ISSUE TITLE
Toolchain location

### ISSUE THREAD

**Issue by thatsitipl** [OpenNuvoton/N32905_Linux_BSP#3]
Where can i download the toolchain used for building?

Best Regards

**Comment by cyliangtw** [comment]
This repo. is only to sync last patch of N329 kernel/driver source code in time.
Normally, user could get the initial installation of BSP & toolchain tar ball from ftp account thru. agent or FAE. `(for ex: ftp://nftp.nuvoton.com/Public/N3290x/SDK/Linux_BSP2.6.35/ )`

If no contact window, how about your company profile ?

**Comment by thatsitipl** [comment]
So there is no way for a private person to get access to the toolchain?

**Comment by cyliangtw** [comment]
In fact, you could generate ARM_toolchain_4.8 by Buildroot in your environment.
Anyway, we need some internal discussion on this kind requirement.

More, where did you get N3290x develop-kit ?
Why choose old kernel version "v2.6.35" ?

**Comment by thatsitipl** [comment]
1. I bought the device from ebay.
2. Because afaik there is no newer kernel available for the N32905U3DN

If you don't provide the toolchain to private persons i'll just try to build my own using crosstool.

**Comment by cyliangtw** [comment]
Please share your e-mail for toolchain & rootfsys deliver.

**Comment by thatsitipl** [comment]
send it to : herbertheinzhuber@gmail.com
